package dev.sharkuscator.obfuscator.transformers.obfuscators.renamers

import dev.sharkuscator.commons.extensions.classNode
import dev.sharkuscator.commons.extensions.getQualifiedName
import dev.sharkuscator.commons.extensions.isAutoGenerated
import dev.sharkuscator.obfuscator.ObfuscatorServices
import dev.sharkuscator.obfuscator.configuration.GsonConfiguration
import dev.sharkuscator.obfuscator.configuration.transformers.RenameConfiguration
import dev.sharkuscator.obfuscator.dictionaries.DictionaryFactory
import dev.sharkuscator.obfuscator.dictionaries.MappingDictionary
import dev.sharkuscator.obfuscator.events.TransformerEvents
import dev.sharkuscator.obfuscator.transformers.BaseTransformer
import dev.sharkuscator.obfuscator.transformers.TransformerPriority
import dev.sharkuscator.obfuscator.transformers.TransformerStrength
import meteordevelopment.orbit.EventHandler
import org.objectweb.asm.tree.ClassNode

object FieldRenameTransformer : BaseTransformer<RenameConfiguration>("FieldRename", RenameConfiguration::class.java) {
    private val disallowedInterfacePatterns = listOf("com.sun.jna.*".toRegex())
    lateinit var fieldMappingDictionary: MappingDictionary<ClassNode>

    override fun initialization(configuration: GsonConfiguration): RenameConfiguration {
        fieldMappingDictionary = DictionaryFactory.createDictionary(super.initialization(configuration).dictionary)
        return this.configuration
    }

    @EventHandler
    @Suppress("unused")
    private fun onFieldTransform(event: TransformerEvents.FieldTransformEvent) {
        if (!isEligibleForExecution() || !shouldTransformField(event.obfuscationContext, event.nodeObject) || disallowedInterfacePatterns.any { it.matches(event.nodeObject.classNode.superName) }) {
            return
        }

        if (event.obfuscationContext.classNodeProvider.isLibraryClass(event.nodeObject.classNode.name) || event.nodeObject.classNode.isAutoGenerated()) {
            return
        }

        if (event.obfuscationContext.isRecognizedAsMinecraftMod && event.nodeObject.name.startsWith("field_")) {
            return
        }

        val fieldMapping = "${configuration.namePrefix}${fieldMappingDictionary.generateNextName(event.nodeObject.classNode)}"
        ObfuscatorServices.symbolRemapper.setMapping(event.nodeObject.getQualifiedName(), fieldMapping)
    }

    override fun transformerStrength(): TransformerStrength {
        return TransformerStrength.MODERATE
    }

    override fun executionPriority(): Int {
        return TransformerPriority.TWENTY_FIVE
    }
}
